project:
  type: website
  output-dir: docs

website:
  title: "Charlotte Imbert"
  navbar:
    left:
      - text: "About Me"
        href: index.qmd
      - text: "Data Viz"
        menu: 
         - text: "Olympics"
           href: olympics.html
         - text: "Premier League"
           href: premierleague.html
         - text: "Shakespeare"
           href: shakespeare.html

format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

