project:
  type: website
  output-dir: docs

website:
  title: "Charlotte Imbert"
  navbar:
    left:
      - text: "About Me"
        href: index.qmd
      - text: "Statistical Analyses"
        menu: 
          - text: "How to Win in Tennis - ATP"
            href: atp.qmd
          - text: "Height and Serve Performance in Tennis - WTA"
            href: wta.qmd
          - text: "Taylor Swift and Kacey Musgraves Lyrical ANOVA"
            href: swift.qmd
      - text: "Machine Learning Projects"
        menu:
          - text: "MLB Bat Speed and Swing Length - Analysis Report"
            href: mlb_pdf.qmd
          - text: "Text Message Classification"
            href: text.qmd
          - text: "Bank Loan Default Prediction"
            href: kaggle_gmsc.qmd
      - text: "Data Visualization"
        menu:
         - text: "Global Tuberculosis Mortality Dashboard"
           href: https://cameraperture.shinyapps.io/dssi_app/
         - text: "MLB Bat Speed and Swing Length - Shiny Dashboard"
           href: https://cameraperture.shinyapps.io/shiny_app/
         - text: "Premier League Fouls"
           href: premierleague.qmd
         - text: "Shakespeare Dialogue"
           href: shakespeare.qmd
         - text: "Olympics Trends"
           href: olympics.qmd
      - text: "Data Science Coursework Projects"
        menu:
          - text: "Acoustic Analytics in SQL"
            href: project4.qmd
          - text: "Home Advantage in English Women's Football"
            href: miniproject3.qmd
          - text: "30 Years of American Anxieties"
            href: miniproject2.qmd
          - text: "Foundations of Data Science Final Presentation"
            href: presentation.qmd

format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

