project:
  type: website
  output-dir: docs

website:
  title: "Charlotte Imbert"
  navbar:
    left:
      - text: "About Me"
        href: index.qmd
      - text: "Statistical Analyses"
        menu: 
          - text: "How to Win in Tennis"
            href: atp.html
      - text: "Data Viz"
        menu: 
         - text: "Olympics"
           href: olympics.html
         - text: "Premier League"
           href: premierleague.html
         - text: "Shakespeare"
           href: shakespeare.html
      - text: "Mini-Project 2"
        href: miniproject2.html
      - text: "Mini-Project 3"
        href: miniproject3.html
      - text: "Project 4"
        href: project4.html

format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

