project:
  type: website
  output-dir: docs

website:
  title: "Charlotte Imbert"
  navbar:
    left:
      - text: "About Me"
        href: index.qmd
      - text: "Statistical Analyses"
        menu: 
          - text: "How to Win in Tennis - ATP"
            href: atp.html
          - text: "Height and Serve Performance in Tennis - WTA"
            href: wta.html
          - text: "Taylor Swift and Kacey Musgraves Lyrical ANOVA"
            href: swift.qmd
      - text: "Data Science Projects"
        menu:
          - text: "SQL"
            href: project4.html
          - text: "Permutation"
            href: miniproject3.html
          - text: "Text Analysis"
            href: miniproject2.html
          - text: "Foundations of Data Science Final Presentation"
            href: presentation.html
      - text: "Machine Learning"
        menu:
          - text: "MLB Bat Speed and Swing Length - Analysis Report"
            href: mlb_pdf.qmd
          - text: "MLB Bat Speed and Swing Length - Shiny Dashboard"
            href: http://cameraperture.shinyapps.io/shiny_app
          - text: "Text Message Classification"
            href: text.qmd
          - text: "Kaggle Give Me Some Credit"
            href: kaggle_gmsc.qmd
      - text: "Data Visualization"
        menu: 
         - text: "Olympics"
           href: olympics.html
         - text: "Premier League"
           href: premierleague.html
         - text: "Shakespeare"
           href: shakespeare.html

format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

