project:
  type: website
  output-dir: docs

website:
  title: "Charlotte Imbert"
  navbar:
    left:
      - text: "About Me"
        href: index.qmd
      - text: "Statistical Analyses"
        menu: 
          - text: "How to Win in Tennis"
            href: atp.html
      - text: "Data Visualization"
        menu: 
         - text: "Olympics"
           href: olympics.html
         - text: "Premier League"
           href: premierleague.html
         - text: "Shakespeare"
           href: shakespeare.html
      - text: "Data Science Projects"
        menu: 
          - text: "SQL"
            href: project4.html
          - text: "Permutation"
            href: miniproject3.html
          - text: "Text Analysis"
            href: miniproject2.html

format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

